create table shoe_sales(Sale_ID  varchar (50),Date date,Brand varchar (50),Shoe_Type varchar(50),Color varchar(50),Country varchar(50),Sales_Channel varchar(50),Price_USD decimal (10,2),Units_Sold decimal(10,2),Revenue_USD decimal(10,2));
select * from shoe_sales;

SELECT
	COUNT(*) AS TOTAL_ORDER
FROM
	SHOE_SALES;

SELECT
	COUNT(*) AS TOTAL_ORDER,
	BRAND
FROM
	SHOE_SALES
GROUP BY
	BRAND;
 
SELECT
	COUNT(*) AS TOTAL_ORDER,
	BRAND,
	DATE_PART('quarter', DATE) AS QUARTER
FROM
	SHOE_SALES
GROUP BY
	BRAND,
	QUARTER
ORDER BY
	TOTAL_ORDER DESC
LIMIT
	5;	
	
SELECT
	COUNT(*) AS TOTAL_ORDER,
	BRAND,
	SHOE_TYPE
FROM
	SHOE_SALES
GROUP BY
	BRAND,
	SHOE_TYPE
ORDER BY
	TOTAL_ORDER DESC
LIMIT
	5;

select * from shoe_sales;

SELECT
	COUNT(*) AS TOTAL_ORDER,
	COUNTRY
FROM
	SHOE_SALES
GROUP BY
	COUNTRY;

SELECT
	COUNT(*) AS TOTAL_ORDER,
	SALES_CHANNEL
FROM
	SHOE_SALES
GROUP BY
	SALES_CHANNEL;
SELECT
	ROUND(AVG(PRICE_USD), 2)
FROM
	SHOE_SALES;
SELECT
	ROUND(SUM(UNITS_SOLD)) AS TOTAL_SOLD_UNIT
FROM
	SHOE_SALES;

SELECT
	ROUND(SUM(UNITS_SOLD)) AS TOTAL_SOLD_UNIT,
	BRAND
FROM
	SHOE_SALES
GROUP BY
	BRAND;

select * from shoe_sales;
SELECT
	SUM(REVENUE_USD) AS TOTAL_REVENUE
FROM
	SHOE_SALES;

SELECT
	SUM(REVENUE_USD) AS TOTAL_REVENUE,
	ROUND(SUM(UNITS_SOLD)) AS SOLD_UNIT,
	BRAND
FROM
	SHOE_SALES
GROUP BY
	BRAND;
	
SELECT
	COUNTRY,
	SUM(REVENUE_USD) AS TOTAL_REVENUE
FROM
	SHOE_SALES
GROUP BY
	COUNTRY;